name: Publish middleware Python package to fury.io

on:
  push:
    # branches:
    #   - master
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Preapre Python code
      # working-directory: . 
      run: pip install --extra-index-url https://pypi.fury.io/dharpa/ -e .
    - name: install 'wheel' package
      run: pip install -U wheel
    - name: create packages
      # working-directory: .
      run: python setup.py sdist bdist_wheel
    - name: upload source package
      # working-directory: . 
      run: curl -F package=@$(ls dist/lumy-middleware-*.tar.gz) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
    - name: upload wheel
      # working-directory: .
      run: curl -F package=@$(ls dist/lumy_middleware-*.whl) https://${GEMFURY_PUSH_TOKEN}@dharpa.fury.land:443/pypi/
